allowBuilds:
  lefthook: true
  sharp: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@kanjou/config@0.0.10'
  - '@kanjou/react@0.0.11'
onlyBuiltDependencies:
  - lefthook
